spring:
  application:
    name: SERVICE-REGISTRY
  server:
    port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
